### ISSUE TITLE
Allow custom configuration of the iPXE menu

### ISSUE THREAD

**Issue by lholota** [homecentral/docker-dhcp#15]
## Option 1 - Configurable menu
- Difficult to set up if I want to customize just a bit?
```yaml
menu:
  - name: "Installations" # Header
  - name: "Install Windows 10" # Item with command
    boot_wim: "../path/to/file.wim"
  - name: "Some really large section"
     submenu: # Navigates to a separate screen
       background_image: "../path/to/file.png"
       items:
         - name: aaaaaaa
            boot_wim: "../etc/.."
```

### Action types
- boot_wim - Boot Windows based wim file
- boot_clonezilla
- boot_ubuntu (?)

** How to do predefined images in combination with custom images? **

## Option 2 - Predefined menu
- Only supports predefined images, may be difficult to add custom Windows images (e.g. Enterprise edition, N edition etc.)
